/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#cbc6bd",
                "surface-container-highest": "#e5e2e1",
                "on-surface-variant": "#444748",
                "on-secondary-fixed-variant": "#494640",
                "secondary-container": "#e7e2d9",
                "on-tertiary-container": "#a99894",
                "surface-tint": "#5f5e5e",
                "surface-container-high": "#eae7e7",
                "primary": "#1e1e1e",
                "on-primary": "#ffffff",
                "error": "#ba1a1a",
                "tertiary-fixed": "#f2ded9",
                "primary-container": "#333333",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "secondary": "#615e57",
                "on-surface": "#1c1b1b",
                "tertiary-fixed-dim": "#d5c3be",
                "primary-fixed-dim": "#c8c6c6",
                "secondary-fixed": "#e7e2d9",
                "inverse-surface": "#313030",
                "surface-dim": "#dcd9d9",
                "inverse-primary": "#c8c6c6",
                "tertiary-container": "#3c312e",
                "on-background": "#1c1b1b",
                "outline-variant": "#c4c7c7",
                "outline": "#747878",
                "on-primary-container": "#9c9b9b",
                "on-primary-fixed": "#1b1c1c",
                "background": "#fcf9f8",
                "on-secondary-fixed": "#1d1b16",
                "surface-container-low": "#f6f3f2",
                "surface": "#fcf9f8",
                "surface-container": "#f0eded",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed": "#231916",
                "primary-fixed": "#e4e2e1",
                "tertiary": "#261c19",
                "surface-bright": "#fcf9f8",
                "on-primary-fixed-variant": "#474747",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f3f0ef",
                "on-secondary-container": "#67645d",
                "surface-variant": "#e5e2e1",
                "on-tertiary-fixed-variant": "#514440",
                "blush-accent": "#f8ecea"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "container-padding": "40px",
                "unit": "8px",
                "stack-sm": "12px",
                "gutter": "24px",
                "stack-md": "24px",
                "stack-lg": "48px",
                "margin-page": "64px",
                "container-max": "1120px",
                "section-gap": "120px"
            },
            fontFamily: {
                "label-sm": ["Work Sans"],
                "label-caps": ["Manrope"],
                "headline-md": ["Noto Serif"],
                "body-md": ["Noto Serif", "Manrope"],
                "body-lg": ["Noto Serif", "Manrope"],
                "headline-xl": ["Noto Serif"],
                "headline-lg": ["Noto Serif"],
                "display-lg": ["Noto Serif"],
            },
            fontSize: {
                "label-sm": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.08em", "fontWeight": "500"}],
                "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-xl": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "400"}],
                "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "700"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
