/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                cream: '#fcf9f5',
                navy: '#031632',
                sage: '#566252',
                blush: '#dcc0c0',
                'navy-light': '#1a2b48',
                'sage-light': '#d6e4d0',
                'sage-dark': '#3e4a3b',
                'surface-warm': '#f0ede9',
                'surface-stone': '#e5e2de',
                gold: '#c9a84c',
                'gold-light': '#f0e6c8',
                // Keep some material colors as fallback just in case other components use them
                "secondary-fixed-dim": "#cbc6bd",
                "surface-container-highest": "#e5e2e1",
                "on-surface-variant": "#444748",
                "on-secondary-fixed-variant": "#494640",
                "secondary-container": "#e7e2d9",
                "on-tertiary-container": "#a99894",
                "surface-tint": "#5f5e5e",
                "surface-container-high": "#eae7e7",
                "primary": "#1e1e1e",
                "on-primary": "#ffffff",
                "error": "#ba1a1a",
                "tertiary-fixed": "#f2ded9",
                "primary-container": "#333333",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-tertiary": "#ffffff",
                "on-secondary": "#ffffff",
                "secondary": "#615e57",
                "on-surface": "#1c1b1b",
                "tertiary-fixed-dim": "#d5c3be",
                "primary-fixed-dim": "#c8c6c6",
                "secondary-fixed": "#e7e2d9",
                "inverse-surface": "#313030",
                "surface-dim": "#dcd9d9",
                "inverse-primary": "#c8c6c6",
                "tertiary-container": "#3c312e",
                "on-background": "#1c1b1b",
                "outline-variant": "#c4c7c7",
                "outline": "#747878",
                "on-primary-container": "#9c9b9b",
                "on-primary-fixed": "#1b1c1c",
                "background": "#fcf9f8",
                "on-secondary-fixed": "#1d1b16",
                "surface-container-low": "#f6f3f2",
                "surface": "#fcf9f8",
                "surface-container": "#f0eded",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed": "#231916",
                "primary-fixed": "#e4e2e1",
                "tertiary": "#261c19",
                "surface-bright": "#fcf9f8",
                "on-primary-fixed-variant": "#474747",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f3f0ef",
                "on-secondary-container": "#67645d",
                "surface-variant": "#e5e2e1",
                "on-tertiary-fixed-variant": "#514440",
                "blush-accent": "#f8ecea"
            },
            fontFamily: {
                serif: ['Noto Serif', 'Georgia', 'serif'],
                sans: ['Manrope', 'system-ui', 'sans-serif'],
                "label-sm": ["Work Sans"],
                "label-caps": ["Manrope"],
                "headline-md": ["Noto Serif"],
                "body-md": ["Noto Serif", "Manrope"],
                "body-lg": ["Noto Serif", "Manrope"],
                "headline-xl": ["Noto Serif"],
                "headline-lg": ["Noto Serif"],
                "display-lg": ["Noto Serif"],
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-in-out',
                'slide-up': 'slideUp 0.4s ease-out',
                'scale-in': 'scaleIn 0.3s ease-out',
                'shimmer': 'shimmer 1.5s infinite',
            },
            keyframes: {
                fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
                slideUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
                scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
                shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
